project:
  type: website
  resources:
    - google16de0092a70a120d.html

website:
  title: "✨ Mariia Seleznova"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: files/cv.pdf

format:
  html:
    theme:
      - minty
      - brand 
    css: styles.css
    toc: true



