project:
  type: website
  resources:
    - googlebeb9be5888371595.html
    - robots.txt

website:
  title: "✨ Mariia Seleznova"
  site-url: https://mselezniova.github.io
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: files/cv.pdf

format:
  html:
    theme:
      - minty
      - brand 
    css: styles.css
    toc: false



